# fallback prompt if the rest cannot be loaded properly:
export PS1="%n@%m %20<...<%d $ "

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey "^R" history-incremental-search-backward

source ~/.aliases

WORKON_HOME=$HOME/.pyenv
PROJECT_HOME=$HOME/Documents/Projekte
source /usr/local/bin/virtualenvwrapper.sh

doge
export VISUAL=nvim
export EDITOR=nvim
export PYTHONSTARTUP=$HOME/.pythonrc

source ~/.zshrc.local

autoload -U add-zsh-hook
load-nvmrc() {
  if [[ -f .nvmrc && -r .nvmrc ]]; then
    nvm use
  fi
}
add-zsh-hook chpwd load-nvmrc

# added by travis gem
[ -f /Users/ohcibi/.travis/travis.sh ] && source /Users/ohcibi/.travis/travis.sh

# autosuggestions
bindkey '' autosuggest-accept

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

test -e /usr/local/share/zsh/site-functions/git-flow-completion.zsh && source /usr/local/share/zsh/site-functions/git-flow-completion.zsh

projects() {
  cd $HOME/Documents/Projekte
}

if [[ -n $ITERM_PROFILE && $ITERM_PROFILE = "Hotkey Window" ]]; then
  export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'
fi

ZSH_HIGHLIGHT_STYLES[cursor]='bg=blue'

source /usr/local/share/zsh/site-functions/_tmuxinator

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

