#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey "^R" history-incremental-search-backward

source ~/.aliases

WORKON_HOME=$HOME/.pyenv
PROJECT_HOME=$HOME/Documents/Projekte
source /usr/local/bin/virtualenvwrapper.sh

doge
export VISUAL=vim
export PYTHONSTARTUP=$HOME/.pythonrc

source ~/.zshrc.local

autoload -U add-zsh-hook
load-nvmrc() {
  if [[ -f .nvmrc && -r .nvmrc ]]; then
    nvm use
  fi
}
add-zsh-hook chpwd load-nvmrc

# added by travis gem
[ -f /Users/ohcibi/.travis/travis.sh ] && source /Users/ohcibi/.travis/travis.sh

# autosuggestions
bindkey '' autosuggest-accept

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
