#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey "^R" history-incremental-search-backward

source ~/.aliases

WORKON_HOME=$HOME/.pyenv
PROJECT_HOME=$HOME/Documents/Projekte
source /usr/local/bin/virtualenvwrapper.sh

doge
export VISUAL=vim
export PYTHONSTARTUP=$HOME/.pythonrc

export EDITOR=vim

export REPORTTIME=5

export NVM_DIR="$HOME/.nvm"

path=(~/bin ~/local/bin /usr/local/heroku/bin $path ~/.rvm/bin)

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

